apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomuselist
  labels:
    app: roomuselist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roomuselist
  template:
    metadata:
      labels:
        app: roomuselist
    spec:
      containers:
        - name: roomuselist
          image: 496278789073.dkr.ecr.ap-southeast-2.amazonaws.com/skccuser1-roomuselist:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5