apiVersion: apps/v1
kind: Deployment
metadata:
  name: roomuseList
  labels:
    app: roomuseList
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roomuseList
  template:
    metadata:
      labels:
        app: roomuseList
    spec:
      containers:
        - name: roomuseList
          image: username/roomuseList:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5